# Site settings
title: "@trx/ui-common"
description: "Biblioteca de componentes Vue compartilhada para o ecossistema TRX Systems"
baseurl: ""
url: "https://ui.trixsystems.io"

# Theme
remote_theme: just-the-docs/just-the-docs

# Logo
logo: "/assets/images/logo.svg"

# Aux links
aux_links:
  "GitHub":
    - "https://github.com/trixsystems/ui"

aux_links_new_tab: true

# Color scheme
color_scheme: light

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive

# Footer
footer_content: "&copy; 2024-2026 <a href='https://trixsystems.io/' target='_blank'>TRIX Systems</a>. Distribuido sob licenca proprietaria."

# Back to top link
back_to_top: true
back_to_top_text: "Voltar ao topo"

# Heading anchor links
heading_anchors: true

# Callouts
callouts:
  warning:
    title: Aviso
    color: yellow
  note:
    title: Nota
    color: blue
  tip:
    title: Dica
    color: green
  important:
    title: Importante
    color: red

# Code copy
enable_copy_code_button: true

# Collections
collections:
  components:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "components"
    values:
      layout: default
      parent: Componentes

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude
exclude:
  - node_modules
  - vendor
